version: "3.3"
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: szakdoga
    volumes:
      - ./php:/var/www/html/
    stdin_open: true
    tty: true
    ports:
      - 8000:80

